export const ADD_CONTACT = "ADD_CONTACT";
export const CHANGE_ADMIN = "CHANGE_ADMIN";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const DISPLAY_DETAILS = "DISPLAY_DETAILS";